01-basics solved
js-tasks-ru/vue-20220419_twangste pull request #3
Opened 2022-04-23 21:11 UTC by twangest

02-VueCalculator
03-MarketList
04-MeetupTitle

2022-04-23 21:12 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-04-25 15:55 UTC, ShGKme requested changes
Чтобы лишний раз попрактиковаться в вычисляемых свойствах предлагается в 01-basics/03-MarkedList поменять решение так, чтобы вместо вызова метода перебора email-ов в шаблоне вычисляемое свойство сразу готовило данные к выводу.

Остальные задачи приняты.

2022-04-25 15:55 UTC, ShGKme commented on 01-basics/02-VueCalculator/index.html
> +        <output class="col">{{result}}</output>
У текстовой интерполяции принято добавлять пробелы: `{{ result }}`

2022-04-25 15:55 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  },
При таком решении в шаблоне при выводе каждого `email` вызывается `isMarked`, который работает очень не эффективно. Перебирает все `email`ы в массиве отфильтрованных почт чтобы проверить, а нет ли там проверяемой.

При этом каждый раз, когда меняется набор почт или значение фильтра, вычисляется заново `this.searchResult`, где проверяется каждый `email` на удовлетворение фильтру.

Получается, что сначала каждый email проверяется при фильтрации, и в этот момент мы как бы уже узнали про **каждый**, подходит ли он под условие маркировки. А потом при выводе опять проверяет каждый email, только уже в списке отфильтрованных, чтобы проверить, а не находится ли он в положительно проверенных ранее.

2022-04-25 15:55 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  },
В результате получается не очень эффективное решение, при котором в шаблоне вызывается метод. Лучше избегать вызова таких методов в шаблоне.

Сам по себе вызов метода в шаблоне уже не очень хорошо - это не декларативно, и заставляет следить, а нет ли у метода проблем с производительностью или побочных эффектов.

Здесь лучше один раз вычислить данные, которые уже готовы для вывода в приложении. Нам не требуется "отфильтрованные почты", ведь выводим мы все. Нам требуется "промаркированные почты", то есть какие-то такие данные, которые для каждой почты позволяют быстро понять, требуется ли её маркировать.

2022-04-25 19:49 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-04-26 10:26 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-04-26 10:26 UTC, merged