02-components/01-counter-button solved
js-tasks-ru/vue-20220419_twangste pull request #4
Opened 2022-04-27 20:02 UTC by twangest

2022-04-27 20:02 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-04-27 20:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-04-27 20:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-27 20:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-27 21:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-27 22:21 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-27 22:50 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-28 19:26 UTC, ShGKme requested changes
В  `02-components/03-MeetupCover` не работает вывод изображения...

2022-04-28 19:26 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  template: `<button type="button" @click='onClickHandler'>{{count}}</button>`,
В текстовой интерполяции обычно добавляют пробелы: `{{ count }}`

2022-04-28 19:26 UTC, ShGKme commented on 02-components/02-MeetupDescription/MeetupDescription.js
> +  template: `<p class="meetup-description">{{this.description}}</p>`,
`this` в шаблоне не нужен, код шаблона выполняется в контексте экземпляра

2022-04-28 19:26 UTC, ShGKme commented on 02-components/03-MeetupCover/MeetupCover.js
>      </div>`,
Описание объектом, где значение - условие добавления того, что описано в ключе - возможность только привязки классов `class="{ 'classname': true }"`

В `style` объект описывает именно стили, где ключ - название стиля, а значение - значение стиля. Например, `style="{ width: '100%' }"`.

Соответственно `--bg-url: url({image})` - некорректное название CSS свойства.

Кроме того, `{image}` здесь - просто строка с фигурными скобками и словом `image`. Оно не заменится на значение переменной `image`.

2022-04-28 20:13 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-04-28 20:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-04-29 12:31 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-04-29 12:32 UTC, merged